/**
 * Nivel básico — equivale a A1–A2 del MCER (Cambridge A2 Key).
 * Contenidos: verbo to be, artículos, plurales, presente simple y continuo,
 * pasado simple, there is/are, posesivos, preposiciones básicas, cuantificadores,
 * comparativos, futuro con going to, modales can/must.
 *
 * Los distractores reproducen errores típicos de hispanohablantes
 * (orden adjetivo-sustantivo, good/well, doble negación, calcos de preposición).
 */
window.BANCO_GRAMATICA = window.BANCO_GRAMATICA || {};
window.BANCO_GRAMATICA.basica = [
    { tema: "Verbo to be", frase: "My sister ___ a nurse at the city hospital.", opciones: ["am", "is", "are"], correcta: 1, explicacion: "«My sister» es tercera persona del singular, así que le corresponde «is»." },
    { tema: "Verbo to be en pasado", frase: "They ___ not at home yesterday evening.", opciones: ["was", "were", "are"], correcta: 1, explicacion: "«They» siempre lleva «were» en pasado. «Was» solo va con I, he, she, it." },
    { tema: "Artículo a / an", frase: "I need ___ umbrella because it's raining.", opciones: ["a", "an", "the"], correcta: 1, explicacion: "«An» va delante de sonido vocálico, y «umbrella» empieza por /ʌ/." },
    { tema: "Plurales irregulares", frase: "There are three ___ playing in the garden.", opciones: ["child", "childs", "children"], correcta: 2, explicacion: "«Child» tiene plural irregular: «children». Nunca «childs»." },
    { tema: "Presente simple, 3ª persona", frase: "She ___ to work by bus every morning.", opciones: ["go", "goes", "going"], correcta: 1, explicacion: "En presente simple, la tercera persona del singular añade -es: «goes»." },
    { tema: "Presente simple negativo", frase: "He ___ like coffee, he prefers tea.", opciones: ["doesn't", "don't", "isn't"], correcta: 0, explicacion: "Con «he» la negación se forma con «doesn't» + infinitivo sin to." },
    { tema: "Presente continuo", frase: "Look! It ___ outside, take your coat.", opciones: ["rains", "is raining", "rain"], correcta: 1, explicacion: "«Look!» indica algo que ocurre ahora mismo, así que toca presente continuo." },
    { tema: "Adverbios de frecuencia", frase: "I ___ late on Sundays.", opciones: ["get up always", "always get up", "get always up"], correcta: 1, explicacion: "Los adverbios de frecuencia van antes del verbo principal: «always get up»." },
    { tema: "There is / there are", frase: "___ any milk left in the fridge?", opciones: ["Is there", "Are there", "There is"], correcta: 0, explicacion: "«Milk» es incontable, así que lleva singular: «Is there any milk?»." },
    { tema: "Some / any", frase: "We don't have ___ bread for breakfast.", opciones: ["some", "any", "a"], correcta: 1, explicacion: "En frases negativas se usa «any»; «some» se reserva para las afirmativas." },
    { tema: "Genitivo sajón", frase: "This is ___ car, not mine.", opciones: ["my sister", "my sister's", "my sisters"], correcta: 1, explicacion: "La posesión se marca con apóstrofo + s: «my sister's car»." },
    { tema: "Pronombres objeto", frase: "Can you help ___ with these bags, please?", opciones: ["I", "me", "my"], correcta: 1, explicacion: "Detrás del verbo hace falta pronombre objeto: «me», no «I»." },
    { tema: "Pasado simple irregular", frase: "We ___ to Paris last summer.", opciones: ["go", "went", "gone"], correcta: 1, explicacion: "«Last summer» exige pasado simple: «went». «Gone» es participio." },
    { tema: "Preguntas en pasado", frase: "___ you enjoy the film last night?", opciones: ["Did", "Do", "Were"], correcta: 0, explicacion: "El auxiliar del pasado simple es «did», y el verbo se queda en infinitivo." },
    { tema: "Modal can", frase: "She ___ swim very well for her age.", opciones: ["can", "cans", "can to"], correcta: 0, explicacion: "Los modales no llevan -s ni «to»: «she can swim»." },
    { tema: "Modal must", frase: "You ___ wear a helmet on this building site.", opciones: ["must", "must to", "musting"], correcta: 0, explicacion: "«Must» va siempre seguido de infinitivo sin «to»." },
    { tema: "Comparativos", frase: "This box is ___ than the other one.", opciones: ["heavy", "heavier", "more heavy"], correcta: 1, explicacion: "Los adjetivos cortos forman el comparativo con -er: «heavier»." },
    { tema: "Superlativos irregulares", frase: "It's the ___ film I have ever seen.", opciones: ["baddest", "worst", "most bad"], correcta: 1, explicacion: "«Bad» es irregular: bad – worse – worst." },
    { tema: "Futuro con going to", frase: "We ___ visit my aunt tomorrow afternoon.", opciones: ["are going to", "go to", "going to"], correcta: 0, explicacion: "La estructura completa es «be + going to + infinitivo»; no se puede omitir el verbo «be»." },
    { tema: "Preposiciones de tiempo", frase: "The class starts ___ nine o'clock sharp.", opciones: ["in", "at", "on"], correcta: 1, explicacion: "«At» acompaña a las horas exactas." },
    { tema: "Preposiciones de tiempo", frase: "My birthday is ___ May, the same week as yours.", opciones: ["in", "at", "on"], correcta: 0, explicacion: "«In» se usa con meses, estaciones y años." },
    { tema: "Preposiciones de lugar", frase: "The keys are ___ the kitchen table.", opciones: ["in", "on", "at"], correcta: 1, explicacion: "«On» indica contacto con una superficie." },
    { tema: "Much / many", frase: "How ___ sugar do you take in your coffee?", opciones: ["many", "much", "lot"], correcta: 1, explicacion: "«Sugar» es incontable, así que se pregunta con «how much»." },
    { tema: "Much / many", frase: "There isn't ___ time left before the train leaves.", opciones: ["many", "much", "a lot"], correcta: 1, explicacion: "«Time» es incontable y la frase es negativa: «much»." },
    { tema: "Verbo + gerundio", frase: "I really enjoy ___ tennis at the weekend.", opciones: ["play", "playing", "to play"], correcta: 1, explicacion: "«Enjoy» siempre va seguido de gerundio (-ing)." },
    { tema: "Verbo + infinitivo", frase: "I want ___ home early today.", opciones: ["go", "going", "to go"], correcta: 2, explicacion: "«Want» rige infinitivo con «to»." },
    { tema: "Imperativo", frase: "___ quiet, the baby is sleeping.", opciones: ["You are", "Be", "Being"], correcta: 1, explicacion: "El imperativo usa el infinitivo sin sujeto: «Be quiet»." },
    { tema: "Demostrativos", frase: "___ shoes are new, I bought them yesterday.", opciones: ["This", "These", "That"], correcta: 1, explicacion: "«Shoes» es plural y está cerca: «these»." },
    { tema: "Was / were", frase: "The weather ___ terrible during our holiday.", opciones: ["was", "were", "is"], correcta: 0, explicacion: "«Weather» es incontable y va en singular: «was»." },
    { tema: "Presente simple vs continuo", frase: "He usually ___ at seven in the morning.", opciones: ["wakes up", "is waking up", "wake up"], correcta: 0, explicacion: "«Usually» marca rutina, y la rutina pide presente simple." },
    { tema: "Have got", frase: "___ you got a pen I could borrow?", opciones: ["Do", "Have", "Are"], correcta: 1, explicacion: "Con «have got» la pregunta se forma invirtiendo «have»: «Have you got...?»." },
    { tema: "Palabras interrogativas", frase: "___ do you go to the gym? — Twice a week.", opciones: ["How much", "How often", "How long"], correcta: 1, explicacion: "«How often» pregunta por la frecuencia." },
    { tema: "Orden adjetivo-sustantivo", frase: "She has bought a ___ for her birthday.", opciones: ["car red", "red car", "cars red"], correcta: 1, explicacion: "En inglés el adjetivo va delante del sustantivo, al revés que en español." },
    { tema: "Concordancia sujeto-verbo", frase: "My parents ___ in Madrid with my grandmother.", opciones: ["lives", "live", "living"], correcta: 1, explicacion: "«My parents» es plural, así que el verbo no lleva -s." },
    { tema: "Artículo the", frase: "My brother plays ___ guitar in a band.", opciones: ["a", "the", "one"], correcta: 1, explicacion: "Los instrumentos musicales llevan «the»: «play the guitar»." },
    { tema: "Ausencia de artículo", frase: "She likes ___ very much, especially jazz.", opciones: ["the music", "a music", "music"], correcta: 2, explicacion: "Hablando en general, los incontables van sin artículo. En español sí diríamos «la música»." },
    { tema: "Voz pasiva básica", frase: "I ___ in Seville in 1998.", opciones: ["am born", "was born", "born"], correcta: 1, explicacion: "«Nacer» se expresa en pasiva y en pasado: «was born»." },
    { tema: "Sugerencias con let's", frase: "___ go to the beach this afternoon!", opciones: ["Let's", "Let us to", "Lets to"], correcta: 0, explicacion: "«Let's» + infinitivo sin «to» sirve para proponer algo." },
    { tema: "Conectores de causa", frase: "I stayed at home ___ I was very tired.", opciones: ["because", "because of", "for"], correcta: 0, explicacion: "«Because» introduce una oración con sujeto y verbo; «because of» va con sustantivo." },
    { tema: "Conectores de contraste", frase: "The hotel was cheap ___ surprisingly comfortable.", opciones: ["but", "because", "so"], correcta: 0, explicacion: "Hay contraste entre barato y cómodo, así que toca «but»." },
    { tema: "Preguntas de precio", frase: "___ does this shirt cost?", opciones: ["How many", "How much", "What"], correcta: 1, explicacion: "El precio se pregunta con «how much»." },
    { tema: "Some / any en preguntas", frase: "Do you have ___ brothers or sisters?", opciones: ["some", "any", "much"], correcta: 1, explicacion: "En preguntas generales se usa «any»." },
    { tema: "Would like", frase: "I'd like ___ a coffee, please.", opciones: ["have", "having", "to have"], correcta: 2, explicacion: "«Would like» va seguido de infinitivo con «to»." },
    { tema: "There was / there were", frase: "___ a big party at their house last night.", opciones: ["There was", "There were", "It was"], correcta: 0, explicacion: "«A big party» es singular, así que «there was»." },
    { tema: "Plurales irregulares", frase: "He brushes his ___ twice a day.", opciones: ["tooth", "teeths", "teeth"], correcta: 2, explicacion: "El plural de «tooth» es «teeth», sin -s." },
    { tema: "Adjetivo vs adverbio", frase: "She sings very ___ for someone so young.", opciones: ["good", "well", "best"], correcta: 1, explicacion: "Para calificar un verbo hace falta adverbio: «well», no «good»." },
    { tema: "Auxiliar do / does", frase: "___ your brother work in this office?", opciones: ["Do", "Does", "Is"], correcta: 1, explicacion: "«Your brother» es tercera persona del singular: el auxiliar es «does»." },
    { tema: "Preposiciones de lugar", frase: "My cousin lives ___ Barcelona with her family.", opciones: ["at", "in", "on"], correcta: 1, explicacion: "«In» acompaña a ciudades, países y espacios cerrados." },
    { tema: "Futuro con will", frase: "I think it ___ tomorrow, the sky looks grey.", opciones: ["rains", "will rain", "is raining"], correcta: 1, explicacion: "Tras «I think» se expresa una predicción con «will»." },
    { tema: "Negación de can", frase: "Sorry, I ___ come to your party tonight.", opciones: ["can't", "don't can", "no can"], correcta: 0, explicacion: "Los modales se niegan directamente: «can't», nunca «don't can»." },
    { tema: "Adjetivos posesivos", frase: "The dog was wagging ___ tail happily.", opciones: ["it's", "its", "his"], correcta: 1, explicacion: "«Its» es el posesivo; «it's» es la contracción de «it is»." },
    { tema: "Preguntas con how old", frase: "___ is your daughter now?", opciones: ["How much old", "How old", "What age"], correcta: 1, explicacion: "La edad se pregunta con «how old», sin el verbo «tener»." },
    { tema: "Verbo to be en pasado negativo", frase: "They ___ at the concert, they stayed at home.", opciones: ["wasn't", "weren't", "didn't"], correcta: 1, explicacion: "«They» + negación en pasado del verbo to be: «weren't»." },
    { tema: "Preposiciones de lugar", frase: "The car is parked ___ the house, next to the door.", opciones: ["in front of", "in front", "front of"], correcta: 0, explicacion: "La locución completa es «in front of» + sustantivo." },
    { tema: "There is / there are", frase: "There ___ two good reasons to accept the offer.", opciones: ["is", "are", "has"], correcta: 1, explicacion: "«Two reasons» es plural: «there are». Nunca se usa «has» aquí." },
    { tema: "Preposiciones de tiempo", frase: "See you ___ Monday morning, then.", opciones: ["in", "at", "on"], correcta: 2, explicacion: "«On» acompaña a días y fechas concretas." },
    { tema: "Much / many", frase: "How ___ eggs do we need for the cake?", opciones: ["much", "many", "lot of"], correcta: 1, explicacion: "«Eggs» es contable en plural, así que «how many»." },
    { tema: "Going to en negativo", frase: "We ___ going to come, we're too busy.", opciones: ["aren't", "don't", "not"], correcta: 0, explicacion: "La negación afecta al verbo «be»: «we aren't going to»." },
    { tema: "Adjetivo vs adverbio", frase: "Please drive ___ , the road is icy.", opciones: ["careful", "carefully", "carefuly"], correcta: 1, explicacion: "El adverbio de «careful» es «carefully», con doble l." },
    { tema: "Presente simple, 3ª persona", frase: "She ___ television every evening after dinner.", opciones: ["watch", "watches", "is watching"], correcta: 1, explicacion: "«Every evening» marca rutina y la tercera persona añade -es: «watches»." },
    { tema: "Pronombres interrogativos", frase: "___ is that woman in the red coat?", opciones: ["Who", "What", "Which"], correcta: 0, explicacion: "«Who» pregunta por personas." }
];
